apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: mak3r/rancher-demo:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: purple
          readinessProbe:
            httpGet:
              port: web
              path: /