spec:
  template:
    spec:
      containers:
        - name: hello-world
          env:
            - name: CONTAINER_COLOR
              value: orange
            - name: TITLE
              value: "Amsterdam Airport Schipol"